### ISSUE TITLE
less an issue more a querie 

### ISSUE THREAD

**Issue by kenziebburke** [davetyson/project4#24]
I noticed in your component that there is a container component im wondering why the use of that rather than just using app.js as typically that is where the components are rendered on page, maybe adding in some pseudo code to describe why this choice was necessary or alternatively just using app.js as the container!

**Comment by davetyson** [comment]
Good question! We did this because App.js is the React component itself, so we let that render and load, and create all our custom code and our actual app inside the Container.js. The App.js is a native load of the React app itself so we just wanted that to load cleanly, then render our components for the app inside the container.

We thought this was a way to go but aren't sure if it's best practice!
